apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-user
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      containerConcurrency: 20
      containers:
      - command:
        - user
        env:
        - name: DLOG
          value: DEBUG
        image: pag3r/hotel-reservations:latest
        name: hotel-reserv-user
        ports:
          - name: h2c
            containerPort: 8086
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
