apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srv-search
spec:
  template:
    spec:
      containerConcurrency: 20
      containers:
      - command:
        - search
        env:
        - name: DLOG
          value: DEBUG
        image: pag3r/hotel-reservations:latest
        name: hotel-reserv-search
        ports:
          - name: h2c
            containerPort: 8082
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
