---
- name: Update and Install system dependencies
  hosts: nodes
  become: yes
  tasks:   
    - name: Update Apt
      apt: 
        update_cache: yes
    
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present


- name: Install Helm on Kubernetes master node
  hosts: master
  become: yes
  tasks:
    - name: Download Helm install script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get_helm.sh
        mode: '0755'

    - name: Install Helm
      command: /tmp/get_helm.sh

