sudo apt install -y nfs-common

---

modprobe nfs

---

sudo systemctl restart kubelet

---

apiVersion: v1
kind: Pod
metadata:
  name: nfs
  labels:
    app: nfs
spec:
  tolerations: 
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: nfs
    image: pag3r/nfs-server:latest
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
    ports:
      - containerPort: 111
        protocol: UDP
      - containerPort: 2049
        protocol: UDP
      - containerPort: 32675
        protocol: UDP
      - containerPort: 32677
        protocol: UDP 
      - containerPort: 111
        protocol: TCP
      - containerPort: 2049
        protocol: TCP
      - containerPort: 32675
        protocol: TCP
      - containerPort: 32677
        protocol: TCP 

    volumeMounts:
      - name: nfs-storage
        mountPath: /nfs-storage
      
      - name: exports
        mountPath: /etc/exports
        readOnly: true
  
  volumes:
    - name: nfs-storage
      hostPath:
        path: /mnt/disks/vol1
        type: Directory
    
    - name: exports
      hostPath:
        path: /nfs-config/export.txt
        type: File
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  type: NodePort
  selector:
    app: nfs
  ports:
  - name: rpc-portmapper-tcp
    protocol: TCP
    port: 111
    targetPort: 111
  - name: nfs-tcp
    protocol: TCP
    port: 2049
    targetPort: 2049
  - name: statd-tcp
    protocol: TCP
    port: 32675
    targetPort: 32675
  - name: mountd-tcp
    protocol: TCP
    port: 32677
    targetPort: 32677
  - name: rpc-portmapper-udp
    protocol: UDP
    port: 111
    targetPort: 111
  - name: nfs-udp
    protocol: UDP
    port: 2049
    targetPort: 2049
  - name: statd-udp
    protocol: UDP
    port: 32675
    targetPort: 32675
  - name: mountd-udp
    protocol: UDP
    port: 32677
    targetPort: 32677


---

mount volume to /mnt/disks/vol1

---

put export.txt in /nfs-config on the hostPath

---

add the nfs provisioner.

$ helm repo add nfs-subdir-external-provisioner https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
$ helm install nfs-subdir-external-provisioner nfs-subdir-external-provisioner/nfs-subdir-external-provisioner \
    --set nfs.server={x.x.x.x} \
    --set nfs.path=/nfs-storage